#pragma once

static const char PAGE[] PROGMEM = R"HTML(<!doctype html>
<html lang="pt-BR">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="theme-color" content="#0b1220">
<title>Estação Meteo</title>
<style>
:root{color-scheme:dark;font-family:system-ui,-apple-system,Segoe UI,sans-serif;background:#0b1220;color:#eef4ff}
*{box-sizing:border-box}body{margin:0}.wrap{max-width:860px;margin:auto;padding:20px 16px 40px}
header{display:flex;align-items:center;justify-content:space-between;gap:16px;margin-bottom:22px}
.brand{display:flex;align-items:center;gap:12px}.mark{display:grid;place-items:center;width:42px;height:42px;border-radius:13px;background:#183753;color:#72e5f5;font-size:24px}
h1{font-size:1.18rem;margin:0;letter-spacing:.01em}h2{font-size:1rem;margin:0 0 14px}.muted{color:#98aac2;font-size:.82rem}.pill{padding:7px 11px;border:1px solid #29445a;border-radius:999px;color:#72e5f5;font-size:.78rem;white-space:nowrap}
.hero{display:grid;grid-template-columns:1.2fr 1fr;gap:18px;align-items:center;padding:24px;border:1px solid #31566c;border-radius:22px;background:linear-gradient(135deg,#153a4b,#132039 70%);box-shadow:0 18px 35px #03091340}
.eyebrow{font-size:.72rem;letter-spacing:.13em;text-transform:uppercase;color:#a8cad9;font-weight:700}.outside{font-size:clamp(3.5rem,12vw,5.4rem);line-height:1.05;font-weight:700;letter-spacing:-.07em;margin:8px 0}.condition{font-size:.94rem;font-weight:600}.hero-right{border-left:1px solid #4c6b7c;padding-left:20px;display:grid;gap:12px}.internet-temp{font-size:1.8rem!important;color:#ffd184}.hero-right strong{display:block;font-size:1.05rem;margin-top:3px}
.weather-now{display:flex;align-items:center;justify-content:space-between;gap:12px}.weather-icon{font-family:'Segoe UI Emoji','Apple Color Emoji','Noto Color Emoji',sans-serif;font-size:2.7rem;line-height:1;flex:none;filter:drop-shadow(0 7px 10px #06101b80)}.weather-icon:empty{display:none}
.section-head{display:flex;align-items:baseline;justify-content:space-between;gap:12px;margin:25px 0 11px}.section-head h2{margin:0}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.card{min-height:122px;padding:16px;border:1px solid #243348;border-radius:17px;background:#111d2e}.label{color:#a1b2c8;font-size:.8rem}.value{margin:12px 0 4px;font-size:clamp(1.4rem,4vw,1.9rem);font-weight:700;letter-spacing:-.04em;white-space:nowrap}.unit{font-size:.75em;color:#a1b2c8;font-weight:500}.meta{color:#98aac2;font-size:.75rem}.cyan{color:#75e5f1}.violet{color:#c9b4ff}.green{color:#a2e7aa}.amber{color:#ffd184}
.alert{margin-top:12px;padding:15px 18px;border-radius:15px;border:1px solid #806638;background:#362a1b;color:#ffe2a6}.alert[hidden]{display:none}.alert strong{display:block;margin-bottom:3px}
.status{display:flex;flex-wrap:wrap;gap:8px;margin:17px 0}.status span{padding:7px 10px;border:1px solid #27394c;border-radius:999px;color:#adbed0;font-size:.75rem}.status .good{color:#9ce3b3;border-color:#315540}.status .bad{color:#ffadb1;border-color:#633c47}
details{margin-top:24px;border:1px solid #27394c;border-radius:17px;background:#111d2e;overflow:hidden}summary{cursor:pointer;padding:17px 18px;font-weight:650;list-style:none}summary::-webkit-details-marker{display:none}summary:after{content:'⌄';float:right;color:#a1b2c8}details[open] summary:after{content:'⌃'}.settings{padding:0 18px 20px}.settings p{margin:0 0 16px}.fields{display:grid;grid-template-columns:1fr 1fr;gap:13px}label{display:block;color:#aebed2;font-size:.81rem;font-weight:600}input{display:block;width:100%;margin-top:6px;padding:12px 13px;border:1px solid #34465c;border-radius:10px;background:#0b1625;color:#eef4ff;font:inherit;outline:none}input:focus{border-color:#72dce9;box-shadow:0 0 0 3px #72dce927}.wide{grid-column:1/-1}.actions{display:flex;align-items:center;flex-wrap:wrap;gap:10px;margin-top:17px}button{min-height:43px;padding:0 17px;border:0;border-radius:10px;background:#30b9d1;color:#071722;font:inherit;font-weight:700;cursor:pointer}button:hover{background:#61d9e9}button.secondary{background:#26374d;color:#e5f3ff}button.secondary:hover{background:#344960}.message{font-size:.81rem;color:#98e6b5}.message.error{color:#ffadb1}footer{margin-top:20px;color:#8298b1;font-size:.74rem}
.city-search{display:flex;gap:8px;margin-top:6px}.city-search input{margin-top:0;flex:1;min-width:0}.city-results{display:grid;gap:7px;margin-top:9px}.city-option{width:100%;min-height:48px;text-align:left;padding:10px 13px;background:#20344b;color:#eef4ff;border:1px solid #3b5672;font-weight:500}.city-option:hover{background:#31516c}.city-choice{margin:9px 0 16px!important;color:#9ce3b3}
@media(max-width:640px){.wrap{padding:16px 12px 32px}.hero{grid-template-columns:1fr;padding:20px;gap:17px}.hero-right{border-left:0;border-top:1px solid #4c6b7c;padding:15px 0 0;grid-template-columns:1fr}.grid{grid-template-columns:repeat(2,minmax(0,1fr))}.card{min-height:112px;padding:13px}.fields{grid-template-columns:1fr}.wide{grid-column:auto}.section-head{margin-top:22px}}
@media(max-width:350px){.pill{display:none}.value{font-size:1.45rem}}
</style>
</head>
<body><main class="wrap">
<header><div class="brand"><div class="mark">◉</div><div><h1>Estação Meteo</h1><div class="muted" id="place">Conectando ao dispositivo…</div></div></div><div class="pill" id="connection">Aguardando dados</div></header>
<section class="hero" aria-label="Temperatura do sensor"><div><div class="eyebrow">Temperatura do sensor</div><div class="outside cyan" id="temperature">-- °C</div><div class="muted" id="bmp-state">BMP581 · leitura local</div></div><div class="hero-right"><div class="eyebrow">Tempo na cidade · Internet</div><div class="weather-now"><strong class="internet-temp" id="outside">--°</strong><div class="weather-icon" id="weather-icon" aria-hidden="true"></div></div><div class="condition" id="condition">Aguardando previsão</div><div><span class="label">Hoje</span><strong id="range">-- / --</strong></div><div><span class="label">Atualizado</span><strong id="updated">--</strong></div></div></section>
<div class="alert" id="rain" hidden><strong id="rain-title"></strong><span id="rain-detail"></span></div>
<div class="section-head"><h2>Leituras</h2><span class="muted" id="clock">--</span></div>
<section class="grid" aria-label="Sensores"><article class="card"><div class="label">Pressão local</div><div class="value violet" id="pressure">--</div><div class="meta" id="msl">Nível do mar --</div></article><article class="card"><div class="label">Altitude estimada</div><div class="value green" id="altitude">--</div><div class="meta">Base barométrica</div></article><article class="card"><div class="label">Umidade externa</div><div class="value amber" id="humidity">--</div><div class="meta">Open-Meteo</div></article></section>
<div class="status"><span id="bmp-chip">BMP581 --</span><span id="qmi-chip">QMI8658 --</span><span id="wx-chip">Previsão --</span><span>Tela: configuração pela web</span></div>
<details><summary>Configurações</summary><form class="settings" id="config-form"><p class="muted">Escolha uma cidade para a previsão. A localização salva substitui a estimativa pelo IP. Deixe a senha vazia para manter a atual.</p><label for="city-query">Cidade</label><div class="city-search"><input id="city-query" autocomplete="off" placeholder="Ex.: Sorocaba"><button type="button" id="city-search">Buscar</button></div><div class="city-results" id="city-results" role="status"></div><p class="city-choice" id="city-choice">Carregando localização…</p><div class="fields"><label>Rede Wi-Fi<input id="ssid" maxlength="32" autocomplete="off" required></label><label>Senha Wi-Fi<input id="pass" type="password" maxlength="64" autocomplete="new-password" placeholder="Manter senha atual"></label><label>Latitude<input id="lat" type="number" min="-90" max="90" step="any" required></label><label>Longitude<input id="lon" type="number" min="-180" max="180" step="any" required></label><label class="wide">Fuso horário<input id="tz" maxlength="63" required></label></div><div class="actions"><button type="submit">Salvar alterações</button><button type="button" class="secondary" id="restart">Reiniciar</button><span id="message" class="message" role="status"></span></div></form></details>
<footer id="foot">Conectando…</footer>
</main><script>
const $=id=>document.getElementById(id);
const weather={0:'Céu limpo',1:'Predomínio de sol',2:'Parcialmente nublado',3:'Nublado',45:'Nevoeiro',48:'Nevoeiro',51:'Garoa',53:'Garoa',55:'Garoa',61:'Chuva fraca',63:'Chuva',65:'Chuva forte',71:'Neve',80:'Pancadas',81:'Pancadas',82:'Pancadas fortes',95:'Tempestade',96:'Tempestade com granizo'};
function weatherIcon(code,isDay){if(code===0)return isDay?'☀️':'🌙';if(code===1)return isDay?'🌤️':'🌙';if(code===2)return isDay?'⛅':'☁️';if(code===3)return'☁️';if(code===45||code===48)return'🌫️';if(code>=51&&code<=55)return'🌦️';if(code>=61&&code<=67)return'🌧️';if(code>=71&&code<=77)return'❄️';if(code>=80&&code<=82)return'🌧️';if(code>=95)return'⛈️';return'🌡️'}
let busy=false;
let chosenCity='';
function show(id,value){$(id).textContent=value}
function chip(id,label,ok){const e=$(id);e.textContent=label+(ok?' OK':' indisponível');e.className=ok?'good':'bad'}
function number(v,d=0){return typeof v==='number'&&Number.isFinite(v)?v.toFixed(d):'--'}
async function update(){if(busy)return;busy=true;try{const response=await fetch('/api/status',{cache:'no-store'});if(!response.ok)throw Error('offline');const r=await response.json();
show('connection',r.net==='AP'?'Modo configuração':'Conectado');if(r.net==='AP'&&!window.apOpened){document.querySelector('details').open=true;window.apOpened=true}show('place',r.loc||'Estação local');show('clock',r.clock||'--');
show('outside',r.wx_desc?number(r.outdoor_temp,1)+'°':'--°');show('weather-icon',r.wx_desc?weatherIcon(r.wcode,r.is_day!==false):'');show('condition',r.wcode===1&&r.is_day===false?'Poucas nuvens':weather[r.wcode]||r.wx_desc||'Sem previsão');show('range',r.wx_desc?number(r.tmin)+'° / '+number(r.tmax)+'°':'-- / --');show('updated',r.wx_desc?`${r.wx_age_min} min atrás`:'Aguardando');
show('temperature',r.bmp_ok?number(r.bmp_temp,1)+' °C':'--');show('pressure',r.bmp_ok?number(r.bmp_press)+' hPa':'--');show('altitude',r.bmp_ok?number(r.altitude)+' m':'--');show('humidity',r.humidity>=0?number(r.humidity)+' %':'--');show('bmp-state',r.bmp_ok?'BMP581 · leitura local ao vivo':'BMP581 · sensor sem leitura');show('msl','Nível do mar '+(r.press_msl>0?number(r.press_msl)+' hPa':'--'));
chip('bmp-chip','BMP581',r.bmp_ok);chip('qmi-chip','QMI8658',r.qmi_ok);chip('wx-chip','Previsão',!!r.wx_desc);
const rain=r.rain_in_h>=0;$('rain').hidden=!rain;if(rain){show('rain-title','☔ '+(r.rain_in_h===0?'Chuva agora':'Chuva em '+r.rain_in_h+' h'));show('rain-detail',(r.rain_prob>=0?r.rain_prob+'% de chance · ':'')+number(r.rain_mm,1)+' mm previstos')}
show('foot','Rede: '+r.net+' · Endereço: '+r.ip+' · Giro: '+(r.gyro||[]).map(v=>number(v)).join(' / ')+' °/s');
}catch(e){show('connection','Sem conexão');show('foot','Não foi possível atualizar. Tentando novamente…')}finally{busy=false}}
function setCity(name){chosenCity=name;show('city-choice',name?'Local escolhido: '+name:'Coordenadas manuais (sem cidade selecionada)')}
async function loadConfig(){try{const response=await fetch('/api/config',{cache:'no-store'});if(!response.ok)throw Error('config');const r=await response.json();$('ssid').value=r.ssid||'';$('lat').value=r.lat??'';$('lon').value=r.lon??'';$('tz').value=r.tz||'';setCity(r.city||'');$('city-query').value=r.city||''}catch(e){show('message','Não foi possível carregar as configurações')}}
async function searchCity(){const query=$('city-query').value.trim(),box=$('city-results');box.replaceChildren();if(query.length<2){box.textContent='Digite pelo menos 2 letras.';return}box.textContent='Buscando cidades…';try{const url='https://geocoding-api.open-meteo.com/v1/search?name='+encodeURIComponent(query)+'&count=8&language=pt&format=json';const response=await fetch(url);if(!response.ok)throw Error('geocoding');const data=await response.json();box.replaceChildren();if(!data.results?.length){box.textContent='Nenhuma cidade encontrada. Tente nome e estado.';return}for(const result of data.results){const name=[result.name,result.admin1,result.country].filter(Boolean).join(', ');const option=document.createElement('button');option.type='button';option.className='city-option';option.textContent=name;option.addEventListener('click',()=>{$('lat').value=result.latitude;$('lon').value=result.longitude;$('tz').value=result.timezone||'UTC';$('city-query').value=name;setCity(name);box.replaceChildren();show('message','Cidade selecionada. Clique em Salvar alterações.')});box.append(option)}}catch(e){box.textContent='Busca indisponível. Verifique a internet ou informe latitude, longitude e fuso manualmente.'}}
$('city-search').addEventListener('click',searchCity);$('city-query').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();searchCity()}});for(const id of ['lat','lon'])$(id).addEventListener('input',()=>{setCity('');$('city-query').value=''});
$('config-form').addEventListener('submit',async e=>{e.preventDefault();const body={ssid:$('ssid').value.trim(),city:chosenCity,lat:Number($('lat').value),lon:Number($('lon').value),tz:$('tz').value.trim()};if($('pass').value)body.pass=$('pass').value;const msg=$('message');msg.className='message';show('message','Salvando…');try{const r=await fetch('/api/config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw Error('save');const saved=await r.json();$('pass').value='';if(saved.restart){show('message','Rede salva. Reiniciando… Conecte à rede escolhida e use o IP mostrado na tela.');await fetch('/api/reboot')}else{show('message','Salvo. Previsão e relógio atualizam em instantes.');update()}}catch(e){msg.className='message error';show('message','Não foi possível salvar.')}});
$('restart').addEventListener('click',async()=>{show('message','Reiniciando…');try{await fetch('/api/reboot');setTimeout(update,5000)}catch(e){show('message','Aguardando a estação voltar…')}});
loadConfig();update();setInterval(update,5000);
</script></body></html>)HTML";
